### ISSUE TITLE
Can ape-x implementation run on multiple machines ?

### ISSUE THREAD

**Issue by gw3691** [neka-nat/distributed_rl#3]
It seems that actors are running on multiple cpu cores on a single machine.
Can they run on multiple machines ?
Thanks in advance.

**Comment by neka-nat** [comment]
Hi @HelloHiGw ,

Thank you for your reporting.
Now, we assume the following configuration:
* PC A(learner node) : ip 192.168.11.2
* PC B(actor node1) : ip 192.168.11.3
* PC C(actor node2) : ip 192.168.11.4

In this case, execute the following:
PC A
```
./run.sh 0 config/learner.conf
```
PC B & C
```
./run.sh 4 config/actor.conf 192.168.11.2
```
