### ISSUE TITLE
why nx_st = np.maximum(self._nx_st, self._cur_st) if self._gray else self._nx_st？ Thanks

### ISSUE THREAD

**Issue by baywc568** [neka-nat/distributed_rl#4]

**Comment by neka-nat** [comment]
Thank you for the question.
I referred to the code below, but it doesn't seem to be in [the original paper](https://web.stanford.edu/class/psych209/Readings/MnihEtAlHassibis15NatureControlDeepRL.pdf), so it may not be needed.
https://github.com/musyoku/deep-q-network/blob/master/agent.py#L58
